import type { Metadata } from 'next'
import { Toaster } from '@/components/ui/sonner'
import { Playfair_Display, Lato } from 'next/font/google'
import { SessionProvider } from 'next-auth/react'
import { auth } from '@/auth'
import './globals.css'
import { getTheme } from '@/lib/actions/theme'
// import Navbar from '@/components/shared/Navbar'
// import Footer from '@/components/shared/Footer'
// import { Toaster } from '@/components/ui/sonner'

const playfair = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-playfair',
  weight: ['400', '700'],
  display: 'swap',
})

const lato = Lato({
  subsets: ['latin'],
  variable: '--font-lato',
  weight: ['300', '400', '700'],
  display: 'swap',
})

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export const generateMetadata = async (): Promise<Metadata> => {
  const { result } = await getTheme()

  return {
    title: result?.title || 'Shoping App',
    description: result?.slogan || 'This is a shoping application',
    openGraph: {
      title: result?.title || 'Shoping App',
      description: result?.slogan || 'This is a shoping application',
      type: 'website',
      url: process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000',
    },
    twitter: {
      card: 'summary_large_image',
      title: result?.title || 'Shoping App',
      description: result?.slogan || 'This is a shoping application',
    },
  }
}

export default async function GlobalLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()

  return (
    <html lang='en'>
      <body
        className={`${playfair.variable} ${lato.variable} antialiased overflow-y-scroll`}
      >
        <SessionProvider session={session}>{children}</SessionProvider>
        <Toaster richColors={true} />
      </body>
    </html>
  )
}
