name: Auto Create PR

on:
  push:
    branches:
      - 'feature/**'
      - 'fix/**'
      - 'hotfix/**'
    branches-ignore:
      - 'main'
      - 'dev'
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Auto PR from ${{ github.ref_name }}'
          commit-message: 'Auto PR from ${{ github.ref_name }}'
          base: main
          branch: ${{ github.ref_name }}
          draft: false
