name: Automatic Pull Request

on:
  push:
    branches-ignore:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Run linter
        run: npm run lint --if-present

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT_TOKEN }}
          base: main
          branch: ${{ github.ref_name }}
          title: "Automatic PR from ${{ github.ref_name }}"
          body: |
            This pull request was generated automatically from branch `${{ github.ref_name }}`.
          draft: false
